services:
  app:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1536M
    environment:
      - ZO_ROOT_USER_EMAIL
      - ZO_ROOT_USER_PASSWORD
      - ZO_TELEMETRY=false
    volumes:
      - app_data:/data
    networks:
      - proxy_apps
volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true